### PR TITLE
Avoid $&, $', and $` if you can (perlfaq6)

### PR DESCRIPTION
**Pull request by ghost**
> Once Perl sees that you need one of these variables anywhere in the program, it provides them on each and every pattern match. That means that on every pattern match the entire string will be copied, part of it to $\`, part to $&, and part to $'. Thus the penalty is most severe with long strings and patterns that match often. Avoid $&, $', and $` if you can, but if you can't, once you've used them at all, use them at will because you've already paid the price. Remember that some algorithms really appreciate them. As of the 5.005 release, the $& variable is no longer "expensive" the way the other two are.

### CODE REVIEW

**Comment by ClintGoss** [comment]
I have just merged this into my own development environment (based on Font::TTF v1.06) and will report any issues ...

**Comment by ghost** [comment]
[Thread](https://www.perlmonks.org/?node_id=11113603) where behavior of those magic variables was discussed for different perl versions. Might be interesting.
P.S. I hope PR message doesn't seems as RTFM. Due to my bad English it is easier for me, to just copy text from FAQ.

**Comment by ClintGoss** [comment]
No problem on the PR message!

Not sure what testing I might do ... this fix applies to 'cmap' table 2 formats, and I'm not even aware what format 'cmap' tables I am currently generating ... will take some digging.

**Comment by bobh0303** [comment]
According to the "Performance issues" section of [Perl 5.30 perlvar](https://perldoc.perl.org/5.30.0/perlvar.html):

> In Perl 5.20.0 a new copy-on-write system was enabled by default, which finally fixes all performance issues with these three variables, and makes them safe to use anywhere.

which suggests this isn't a problem for modern Perl. Am I misunderstanding something?

**Comment by bobh0303** [comment]
According to the "Performance issues" section of [Perl 5.30 perlvar](https://perldoc.perl.org/5.30.0/perlvar.html):

> In Perl 5.20.0 a new copy-on-write system was enabled by default, which finally fixes all performance issues with these three variables, and makes them safe to use anywhere.

which suggests this isn't a problem for modern Perl. Am I misunderstanding something?

**Comment by ghost** [comment]
> According to the "Performance issues" section of [Perl 5.30 perlvar](https://perldoc.perl.org/5.30.0/perlvar.html):
> 
> > In Perl 5.20.0 a new copy-on-write system was enabled by default, which finally fixes all performance issues with these three variables, and makes them safe to use anywhere.
> 
> which suggests this isn't a problem for modern Perl. Am I misunderstanding something?

Yes. You can read more on perlmonks from link I provided earlier. But rather old perl still exist, for example at Centos 7

**Pull request merged**
